version: "3"
services:
  ganache:
    image: omkarpatange/cvs-ganche:tagname
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
    volumes:
      - blockchain_data:/app

  truffle:
    build:
      context: .
      dockerfile: Dockerfile.truffle
    depends_on:
      - ganache
    volumes:
      - blockchain_data:/app

volumes:
  blockchain_data:
